### ISSUE TITLE
Terminal corruption with pry

### ISSUE THREAD

**Issue by apsey** [edporras/edn_turbo#3]
On MacOS, pry 0.10.3, ruby 2.3.3, iTerm2

`pry -r edn_turbo`

Causes the terminal to make `C-c` exit `pry` directly and iTerm to don't break lines anymore when I hit `return` and when I press `arrow-up`, no commands are shown, but they are executed if I press `return`.

On the other hand, `irb -r edn_turbo` works as expected.

FYI: My dirty fix was to have a `Signal.trap('SIGINT') { puts '' }` when launching the `pry` console.

**Comment by edporras** [comment]
What version of MacOS? Does his happen in your Terminal.app as well? What about with the latest pry? 

I'm not seeing the problem on 10.12.5 / Terminal.app and just installed it on Ruby 2.3.3 (pry 0.10.4):

```sh
ep@mocha ~ $ gem list | grep edn_turbo
edn_turbo (0.5.1)
ep@mocha ~ $ pry -r edn_turbo
[1] pry(main)> 
```

I don't have iTerm installed. Will try it later this weekend but I don't know why it would be iTerm-specific. Ideas?

**Comment by apsey** [comment]
I will try to update the versions to the ones you specified and test again. Will post the results later.

**Comment by apsey** [comment]
Running MacOS 10.11.6, pry 0.10.4, ruby 2.3.3p222 and edn_turbo 0.5.1:

Same problem in `iterm2` and `terminal.app`. I am upgrading my MacOS to `10.12.5` and will test again later on.

Btw, have you tried exactly running:
```
ep@mocha ~ $ pry -r edn_turbo
[1] pry(main)> 
```

And inside the prompt pressing `Ctrl+c` or `^C`?

**Comment by apsey** [comment]
```
Signal.trap('SIGINT') { raise Interrupt }
```

Brought us to the same functionality we had previously.

**Comment by edporras** [comment]
Hi, I was able to reproduce the problem but I don't know if there's anything I can do about it as I'm really not doing much. I will make a small release to replace some deprecated calls in the C API but it didn't fix things.

Maybe this is an issue with pry:

https://github.com/pry/pry/issues/1275

Sorry but I don't have time to look into this further as I'm swamped for the next few weeks.

**Comment by edporras** [comment]
Oh, haha, I just saw your comment at the bottom of that thread! 😐

**Comment by edporras** [comment]
BTW, I tried raising `rbInterrupt` from my signal handler but it causes a segmentation fault from within `pry` so I don't think I should leave that in there.

**Comment by apsey** [comment]
No problem, my dirty fix is working just fine :)

**Comment by edporras** [comment]
Closing for now.
