### ISSUE TITLE
Homebrew now installs in /opt/homebrew, so the native config no longer works

### ISSUE THREAD

**Issue by caleb** [edporras/edn_turbo#9]
I just got a new Mac and was surprised to find that the default location for Homebrew is now /opt/homebrew

This makes sense since there were conflicts with the original /use/local location, but it prevented edn_turbo from compiling.

The location of `pkg-config` is hardcoded to `/usr/local/bin/pkg-config`.

I did a quick patch on a fork that uses the mkmf `pkg_config()` function and sets the `PKG_CONFIG_PATH` to look for icu4c in /usr/local and /opt/homebrew locations:

https://github.com/caleb/edn_turbo/blob/55ab642bd10f71664f7be4370b8e66052390a7ba/ext/edn_turbo/extconf.rb#L27-L34

I don't know if you need to run `pkg-config` manually like you are doing currently, so I don't want to make a PR quite yet, but the above configuration seems to work.

**Comment by edporras** [comment]
Hi, thanks so much for reporting this. I don't have a new Mac yet but I tried it out on my Catalina system and it seems to work with homebrew still in `/usr/local` as well as Ubuntu via docker. If you'd like to do a PR, I'll merge and do a release.

**Comment by caleb** [comment]
I've created a new PR: #10
